  
---
- name: Add User
  hosts: all
  become: true
  tasks:
    - name: Create User Name
      user:
        name: "{{ USER_NAME }}"
    - name: Change Password
      user:
        name: "{{ USER_NAME }}"
        password: "{{ PASSWORD | password_hash('sha512') }}"
    - name: Add sudoers.d 
      copy:
       content: |
         %{{USER_NAME}} ALL=(ALL) NOPASSWD: ALL
       dest: "/etc/sudoers.d/{{USER_NAME}}"
       owner: root
       group: root
       mode: 0440
       validate: "/usr/sbin/visudo -c -f '%s'"
